import { CharacterClass } from './properties/race_and_classes';
import { AbilitiesMap } from './properties/abilities/ability_types';
import { ModifiableProperty, BaseProperty, CreatureSize, ListOfSpecialProperties, GearItem } from './00_property';
import { ArmorClass } from './properties/armorClass';
import { Skill } from './properties/skills';
import { SpellCasting } from './spells';
import { Status } from './state/state';
import { SavesMap } from './properties/saves';
import { BodySlotsMap, Item } from './gear/items/items';
import { BaseEffect, EffectData } from './state/effects';
import { Weapon } from './gear/weapons/weapons';
import { UpdateHpCallback, OnCastSpellCallback } from './manipulation_types';

export interface ICharacter {
    docId: string;
    lines: string[];
    sectionLines: Record<string, string[]>;
    parseSuccess: boolean;
    parseErrors: string[];
    parseWarnings: string[];
    name: string;
    rolzRoomId?: string;
    size: CreatureSize;
    abilities: AbilitiesMap;
    bodySlots: BodySlotsMap;
    spellCasting: SpellCasting;
    race: string;
    classes: CharacterClass[];
    skills: Skill[];
    statuses: Status[];
    actions: string[];
    feats: EffectData[][];
    flaws: EffectData[][];
    battleGear: Item[];
    possessions: Item[];
    bab: ModifiableProperty;
    acp: ModifiableProperty;
    specialAttacks: Record<string, ModifiableProperty>;
    resistances: string;
    hp: { current: number; max: number };
    HD: number;
    temporaryHp: number;
    damageBonus: ModifiableProperty;
    weapons: Weapon[];
    Special: ListOfSpecialProperties;
    speed: ModifiableProperty;
    partyName: string | null;
    partyMembers: string[];
    quickStatuses: string[];
    partyNickname?: string | null;
    InitiativeBonus: ModifiableProperty;
    attacksOfOpportunity: ModifiableProperty;
    ac: ArmorClass;
    saves: SavesMap;
    manipulationCallbacks: {
        UpdateHp: UpdateHpCallback[];
        OnCastSpell: OnCastSpellCallback[];
    };

    ParseCharacter(): void;
    GetNamedProperty(propertyName: string): any;
    registerProperty(name: string, property: BaseProperty<any>): void;
    GetModifiableProperty(propertyName: string): ModifiableProperty;
    HasPropertyInitialized(propertyName: string): boolean;
    QueuePendingEffect(propertyName: string, effect: BaseEffect): void;
    ApplyPendingEffects(propertyName: string): void;
    ResolveAllRemainingPendingEffects(): void;
    registerItem(item: GearItem): void;
    addGearEffect(statusName: string, pattern: string, effect: BaseEffect | EffectData): void;
    HasFeat(featName: string): boolean;
    HasStatus(statusName: string): boolean;
    HasClass(className: string): boolean;
    GetClassLevel(className: string): number;
    HasFlaw(flawName: string): boolean;
    InflictDamage(amount: number): void;
    CureDamage(amount: number): void;
    OnRoundsElapsed(amount: number): Status[];
    LogParseError(errorMessage: string): void;
}
